owner: anishk92        # Replace with your GitHub username or org
repo: anishk92-status    # Replace with your Upptime repo name

sites:
  - name: TechboltX
    url: https://techboltx.com

  - name: TechBoltX - RSS Feed
    url: https://feeds.feedburner.com/techboltx

  - name: IPv4 IP test
    url: 185.151.30.224
    port: 80
    check: "tcp-ping"
    ipv6: false

  - name: TechBoltX SMTP Server
    url: smtp.techboltx.com
    port: 25
    check: "tcp-ping"
    ip: 185.151.30.224

status-website:
  cname: status.techboltx.com  
  # baseUrl: /techboltx-upptime  # Uncomment if you don't use custom domain

  logoUrl: https://techboltx.com/wp-content/uploads/2025/04/ChatGPT-Image-Apr-7-2025-06_13_35-PM_11zon-1.png
  name: TechBoltX Uptime Monitor

  introTitle: "**TechBoltX Uptime Monitor**"
  introMessage: "This status page is powered by **Upptime** using GitHub Actions and Pages. Stay informed with real-time uptime monitoring."

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/TechBoltXUser/techboltx-upptime
